spring.application.name=RestAPIs

spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/StudentDatabase
spring.datasource.username=postgres
spring.datasource.password=satyam

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



